### ISSUE TITLE
Adapt healthcheck endpoint from bLink to SFTI

### ISSUE THREAD

**Issue by rolfwagner** [swissfintechinnovations/ca-payment#1]

**Comment by rolfwagner** [comment]
An API Health Check returns information about the operational status of an API.

Basically, anything that could prevent the API from functioning correctly can / should be tested.

The simplest check is a PING, which only responds with a 200 OK message.
Afterwards, extended test queries can be made, which also give indications whether not only the API is reachable, but also gives meaningful feedback.

Further procedure:
- Elaboration of a proposal for a flexible health endpoint (generic for common api). @dkoeni 
- Definition of general parameters (response format, recommendation for use). @dkoeni 
- PR with proposed health check for payment / accounts. @dkoeni

**Comment by svenbiellmann** [comment]
Healthcheck endpoints will be part of next major version (v4). The concrete proposal will come from @simonmeyerm. If there's no change to the current version on the bLink API, the version will be taken.

**Comment by svenbiellmann** [comment]
### Meeting Notes 2.11.23
@simonmeyerm will check if the approach is still to be followed and if the pull request is up to date.

**Comment by svenbiellmann** [comment]
### Meeting Notes 7.12.23

The participants have stated that the approach is reasonable. Jürgen mentioned that requests for other overarching functionalities were raised and addressed to him. 

For the health check SIX will provide a draft.

This issue in the XS2A board will be closed.
