### ISSUE TITLE
Enhance Transactions with Booking-State and subsequently Balance-Types

### ISSUE THREAD

**Issue by simonmeyerm** [swissfintechinnovations/ca-payment#115]
### Contact Details

simon.meyer@six-group.com

### Issue category

Enhancement

### Issue description

The query parameter "bookingStatus" has already been added to the API with the filter values "booked, pending, both". 
However, several issues and adjustments need to be addressed to fully support the functionality. 

**Parameter**
The "bookingStatus" is currently defined as followed:
```
        - in: query
          name: bookingStatus
          required: true
          schema:
            type: string
            enum:
              - booked
              - pending
              - both
```

**Response**
The "bookingStatus" of transactions should be reflected in the response to identify the status. This status is only applicable for intraday data.

**Balance**
The usage of the bookingStatus should be reflected in the retrievable balance of the accounts. 
To be conform with the Swiss Payment Standard guidelines, the following values are used and could be enhanced with:

ITAV - Interim Available

- Definition according to ISO20022: Available balance calculated in the course of the account servicer's business day, at the time specified, and subject to further changes during the business day. The interim balance is calculated on the basis of booked credit and debit items during the calculation time/period specified. 
- Purpose: Provides a real-time snapshot of available funds, subject to change as transactions are processed throughout the day.
- Use Case: Useful for real-time decision-making and managing immediate cash flow needs.

ITBD - Interim Booked:

- Definition according to ISO20022: Balance calculated in the course of the account servicer's business day, at the time specified, and subject to further changes during the business day. The interim balance is calculated on the basis of booked credit and debit items during the calculation time/period specified. 
- Purpose: Offers a static and historical view of the account's balance, considering only completed and recorded transactions.
- Use Case: Useful for reconciling the account and understanding the confirmed and cleared transactions at a specific point in time

XPCD - Expected:

- Definition according to ISO20022: Balance, composed of booked entries and pending items known at the time of calculation, which projects the end of day balance if everything is booked on the account and no other entry is posted. 
- Purpose: Provides a forecast of the balance at the end of the business day, assuming all pending transactions are processed.
- Use Case: Useful for financial planning and anticipating end-of-day balances for operational purposes.

### Issue reasoning

Requirement that was brought up within the bLink Multibanking initiative to improve the user experience. 
Users should have access to real time data, ideally the same in the Service User application as in the e-Banking of the Service Provider. The API currently only supports the request of booked transactions. Users should have access to all bookings and be able to identify and filter them accordingly to better manage their finances. 

### Request

To include the bookingStatus in the current API, the following items and questions must be clarified.

**Query Parameter**
The query parameter is already integrated in the specification. However, the definition should be adjusted. 
Should the bookingState be required?
Should a default value be set and if so, which?

**Response**
The bookingStatus should be reflected in the "Account Transaction Entry" object of the response, even though it is only applicable for Intraday Transactions

**Balance Types**
The balanceType in the /balance endpoint should be extended with ITAV and/or XPCD 

### Proposed change

There are two possibilities to realize the adjustments:

1. Enhance the existing endpoints
- Adjust the existing endpoints to include the bookingStatus parameter and update the response schema accordingly.

2. Add new endpoints for intraday data
-  Create new endpoints specifically for intraday data, either combining balance and transactions according to camt.052 or dividing them into separate endpoints.

### Affected API's

AIS

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by svenbiellmann** [comment]
### Meeting Notes 15.8.24

@simonmeyerm elaborates the change request. In the SFTI specs the attribute "booking state" already exists on the request. On the response this attribute needs to be added. 

Following details were agreed:
- The booking state will be extended on the response of the existing endpoint
- By the request the booking status will be set to optional. Default is "booked"
- Balance type will just reflect the booked transaction and not include the "pending" transactions. 

The Pull Request will be prepared by @simonmeyerm and discussed on next meeting.

**Comment by svenbiellmann** [comment]
### Metting Notes 26.9.24

The name of element will be changed from bookingStatus to entryStatus (alignment with ISO), values with booking and pending added and description changed in line with the change. The Pull Request has been prepared and will be published and reviewed on next meeting 31st October.

**Comment by svenbiellmann** [comment]
### Meeting Notes 31.10.24

The Pull Request has been approved and will be merged into V5. The issues will then be closed.

**Comment by svenbiellmann** [comment]
The pull request was merged into the V5 branch. This issue can therefore be closed.
