### ISSUE TITLE
Clarification of release number

### ISSUE THREAD

**Issue by CommonAPI-Admin** [swissfintechinnovations/ca-payment#119]
### Contact Details

juergen.petry@swissfintechinnovations.ch

### Issue category

Not applicable

### Issue description

Line 467 of the XS2A-yaml contains the following text :

        **NOTE:** This property will become mandatory with the next major release of this API.

Here, a specific release number should be specified.

### Issue reasoning

The current statement is useless

### Request

Please add version number

### Proposed change

```oasv2-yaml
<<<<<<< Section As-Is

========

>>>>>>> Section To-Be
```

### Affected API's

AIS

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by svenbiellmann** [comment]
### Meeting Notes 26.9.24

The comment in the description shall state precisely which version is meant. Just documentary change. The Pull Request / Bug Fix will be prepared by @svenbiellmann and discussed on next meeting.

**Comment by svenbiellmann** [comment]
### Meeting Notes 31.10.24

The Pull Request has been approved and will be merged into V4.1.1.
