### ISSUE TITLE
Cleanup of documentation

### ISSUE THREAD

**Issue by svenbiellmann** [swissfintechinnovations/ca-payment#122]
### Contact Details

sven.biellmann@finnova.com

### Issue category

Documentation

### Issue description

Two small documentation errors were detected.

### Issue reasoning

Improving documentation for better comprehensibility.

### Request

Improve the following two minor documentation issues:

1) Rename property "transactionType" to "entryType" in AccountTransactionEntry object
2) Delete title in remittanceInformation property

<img width="871" alt="image" src="https://github.com/user-attachments/assets/597b2ca5-2ce5-4477-bd11-20cc18fe7b93">

### Affected API's

AIS

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by svenbiellmann** [comment]
### Meeting Notes 26.9.24

Simon will investigate on the usage and possible alignment of transactionType in AccountTypeEntry. An update will be provided on next meeting by @simonmeyerm.

**Comment by svenbiellmann** [comment]
### Meeting Notes 31.10.24

This issue will be postponed and discussed on the next meeting.

**Comment by simonmeyerm** [comment]
After clarification with the SIX payment standards team, the element "transactionType" corresponds to the "CdtDbtInd" in SPS/ISO-20022 and it is required to be used on C- and D-Level for transactions. It is even recommended to use it for all amount and balance fields like "charges" and "interest" to avoid beeing forced to work with positive or negative amounts (+/-). Reason is that certain transaction types require different

**Comment by svenbiellmann** [comment]
### Meeting Notes 12.12.24

The issue will be partially implemented, including part 2 with documentational change. The Pull Request will be prepared and presented for final approval.

**Comment by svenbiellmann** [comment]
Pull request merged into v5 branch.
