### ISSUE TITLE
Order of Headers/Paths/Queries

### ISSUE THREAD

**Issue by simonmeyerm** [swissfintechinnovations/ca-payment#19]
Would it makes sense to order the Headers, Paths and Queries in a defined order for all APIs?

bLink suggestion would be to arrange it alphabetically with:
- Headers required
- Headers optional
- Paths required
- Paths optional
- Queries required
- Queries optional

For bLink the order would look like this:
- bLink Headers required
- bLink Headers optional
- General Headers required
- General Headers optional
- Paths required
- Paths optional
- Queries required
- Queries optional

**Comment by svenbiellmann** [comment]
All SFTI API specifications will follow the proposed naming conventions. For more details please see here: https://github.com/swissfintechinnovations/.github/wiki/Naming-Conventions. Therefore this issue will be closed.

**Comment by svenbiellmann** [comment]
Close of issue without implementation has been approved by the working group.
