### ISSUE TITLE
GET /iso20022/statements - Add date and IBAN to list

### ISSUE THREAD

**Issue by ochatelain** [swissfintechinnovations/ca-payment#22]
IS
- The TPP/Service Users has to parse filenames per bank to know the camt.053 period affected.

SHOULD
- Extend "iso20022ReportReference" with "date" and "iban" to carry the information in a structured way

Proposal: Mapping
| Field JSON | Source (camt.053) | Example |
|---|---|---|
| fromDate | //Stmt/FrToDt/FrDtTm | <FrDtTm>**2023-04-01**T00:00:00</FrDtTm> |
| fromDate | //Stmt/FrToDt/ToDtTm| <ToDtTm>**2023-04-03**T23:59:59</ToDtTm> |

Proposal: Response
```json
      {
      "name": "CH1100790016123456029_2023-01-16",
      "description": "Kontoauszug von CH1100790016123456029 am 16.01.2023",
      "type": "CAMT53",
      "id": "8265333",
      "account": {
         "type": "IBAN",
         "identification": "CH9300762011623852957"
      },
      "dateFrom" : "2023-01-16",
      "dateTo:" : "2023-01-16"
   },
```

Proposal: Swagger

```yaml
        account:
          $ref: '#/components/schemas/paymentIbanAccount'
        dateFrom:
          type: string
          format: date
          example: "2018-10-29"
        dateTo:
          type: string
          format: date
          example: "2018-10-29"
```

**Comment by mew-zh** [comment]
This topic will be discussed at the SASFS TK STM workshop on 15-June-2023.

**Comment by mew-zh** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Proposal: Mapping</p>

Field JSON | Source (camt.053) | Example
-- | -- | --
fromDate | //Stmt/FrToDt/FrDtTm | 2023-04-01T00:00:00
_**to**_Date | //Stmt/FrToDt/ToDtTm | 2023-04-03T23:59:59


</body>
</html>

Note: based on ISO 20022 the "toDate" can also be 24:00:00 to indicate the end of the day despite any  leap second.

**Comment by mew-zh** [comment]
Update from SASFS TK STM:

- best practice for file naming in work
- inclusion of IBAN (or account number) for files and documents relating to one account will be part of it
- camt.05x are according to the Swiss Payment Standards single account messages (camt.053 base massage would also support multiple accounts.
==> therefore, IBAN as part of the file name of a camt.05x is common practice and strongly recommended. 
==> but only a market  practice (like the common API) could enforce this

**Comment by dschoeni** [comment]
Please do not include metadata into the filename. Strings are no suitable replacement for structured information as mentioned in the original proposal by @ochatelain, but are easily broken conventions and lead to mistakes and errors.

The filename can be arbitrary, the metadata should be delivered in a structured and specified format.

**Comment by dschoeni** [comment]
> As mentioned above, the account statement based on the Swiss Payment Standards contains only a statement of one account.

Yes, but the current endpoint returns **all statements for all accounts** valid in the consent. Which is why it isn't possible to distinguish what specific account a file includes, unless it is fetched and inspected.


I don't really understand the rest of your response unfortunately, could you provide an example for clarity?

**Comment by mew-zh** [comment]
@dschoeni 
I will setup a call. Are you available next week (eg. 08. August)

**Comment by svenbiellmann** [comment]
@simonmeyerm to come up with an implementation proposal.

**Comment by svenbiellmann** [comment]
Clarify dependency to issue no. 1 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/43fddc84-9886-4690-85f7-82f47c5da394)

**Comment by simonmeyerm** [comment]
SIX agrees to the above proposal, but have additional suggestions for adjustments to the endpoint as described below. 

**iso20022ReportReference - Elements**

```
{
	"name": "CH1100790016123456029_2023-01-16", //No longer necessary /SIX suggestion -> remove
	"description": "Kontoauszug von CH1100790016123456029 am 16.01.2023", //No longer necessary /SIX suggestion -> remove
	"type": "CAMT53", //No longer necessary /SIX suggestion -> remove
	"schemaVersion": "string" //Pattern could be defined e.g.: camt.053.001.XX / SIX suggestion -> string
	"id": "8265333", //Alternative ReportId
	"account": { 
		"type": "IBAN",
		"identification": "CH9300762011623852957" //Alternative AccountId
	},
	"dateFrom" : "2023-01-16",
	"dateTo:" : "2023-01-16"
},
```
**ISO20022/statements**
Query parameters for the request could be added in order to limit the list of entries:

- accountId - optional
- dateFrom - optional
- dateTo - optional

Suggestion open for discussion.

**Comment by svenbiellmann** [comment]
### Meeting Notes 2.11.23
The final proposal for extending the date, IBAN and the camt scheme version on this endpoint will be provided by SIX.

There is clarification required at Service Provider to check if the three additional elements can be implemented and populated by autumn 2024 (V4).

The introduction of additional query parameters (account ID, date from, date to) will be subject for discussion in V5.  

**Action Point**
@ Service Provider: To check if the implementation and population of the three additional elements can be done by autumn 2024 (V4).

**Comment by svenbiellmann** [comment]
### Meeting Notes 7.12.23

It was agreed that these changes will be implemented for V4 (November 2024) as optional, in order to provide sufficient implementation time to all Service Providers. With the new major version V5 in November 2025 the setting of these elements will change to mandatory. 

The pull request for the additional optional new elements will be drafted and presented on the next working group meeting. All other changes coming in V5 will be raised in a new issue.
