### ISSUE TITLE
Allign Account Item to deliver the same information (accountOwner, allowedCurrencies)

### ISSUE THREAD

**Issue by svensson13** [swissfintechinnovations/ca-payment#23]
The SIX API version includes the GET /consent endpoint. The content of this endpoint is very similar to the GET /accounts/{accountID} endpoint but it contains two additional attributes "accountOwner" and "allowedCurrencies". Which leads to the following questions:
- Why are there two different endpoints which provide almost the same information? Wouldn't one be enough?
- How are the attributes "accountOwner" and "allowedCurrencies" specified from a business point of view? Who is "accountOwner" in a joint account? What does "allowedCurrencies" actually mean?
- For what reason are these two additional attributes needed?

**Comment by MHamburgerCH** [comment]
- The AccountOwner is in a joint account eg "Ms X and/or Mr X".
- This information is needed for Compliance-Processes (identification of the owner)

**Comment by svenbiellmann** [comment]
Will be added in version 4.0, pull request already exists.

**Comment by chatelao** [comment]
Was heisst das für den "/consent" Endpunkt für v4? Welche Variante verfolgen wir:

a) Die Inhalte in allen Antworten (AIS und PSS) glattziehen (meine Präferenz)
b) Den "/consents" Endpunkt in AIS und PSS entfernen und überall durch "/accounts" ersetzen (Grüne-Wiesen-Bild).

**Comment by svenbiellmann** [comment]
Align all endpoints containing the "account" item to deliver the same information. That means, that with v4 all account Items will have a property "accountOwner" and "allowedCurrencies". Property "accountOwner" will be set to mandatory.

**Comment by svenbiellmann** [comment]
Relates to issue no. 5 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/0211055a-9743-4560-8acf-ae4518d36abb)

**Comment by svenbiellmann** [comment]
### Meeting Notes 2.11.23
The proposal for extension of elements in all endpoints was agreed.

**Comment by svenbiellmann** [comment]
### Meeting Notes 7.12.23

The pull request was approved. Additionally, the character string for element AccountOwner shall be extended from 70 to 140 characters. Due to backward compatibility no impact is expected.
