### ISSUE TITLE
Adapt description for the “designation” field in the account item

### ISSUE THREAD

**Issue by juergen-petry** [swissfintechinnovations/ca-payment#28]
**Problem Description**
Since the designation field in the bLink API is specified as optional and a Service Provider might choose not to send this information, a Service User would only receive the IBAN and currency as information per account to display in the front-end of their Multibanking offering. Especially Retail clients might struggle to differentiate their accounts only based on these information.

**Request**
Make the designation field mandatory, so that a Service User for sure receives this information from any Service Provider and is able to display it to their clients in the front-end.

**Remark**
This issue was raised on behalf of Majurikka Sivanantham (majurikka.sivanantham@ubs.com), who is not allowed to register on GitHub due to access restrictions imposed by her employer.

**Comment by ochatelain** [comment]
Do you really mean **TPP** (Third Party / FinTech) or ASASP/SP (Bank / Financial Institution?

**Comment by juergen-petry** [comment]
Thanks for this notice, dear Oli! Error is corrected.

**Comment by ochatelain** [comment]
You're welcome.

**Comment by svenbiellmann** [comment]
Implementation proposal will be worked out until the next working group meeting

**Comment by svenbiellmann** [comment]
Relates to issue no. 17 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/bcf5fe78-b1cb-403e-90e0-18eba4c2b3f3)

**Comment by RaulGuirao** [comment]
The results of the first analysis were summarized in the attached document.

On the SFTI meeting on 2nd November following questions need to be discussed and clarified:
A)	Shall this data be provided mandatorily? --> Change
B)	In case no account designation (alias) was defined by user what shall be provided? Shall the bank be allowed to capture the bank specific account type (Konto Rubrik)?
This is probably common implementation at the present by the banks. --> Probably no change

[SFTI XS2A_GitHub Number 28_Account Designation_2023-11_V0-1.pdf](https://github.com/swissfintechinnovations/ca-payment/files/13189953/SFTI.XS2A_GitHub.Number.28_Account.Designation_2023-11_V0-1.pdf)

**Comment by svenbiellmann** [comment]
The existing field for "designation" (XML: Account/Name; JSON: designation) will be kept optional. 

A strong recommendation for mandatory usage shall be provided to Service Provider. This element shall be populated with the account alias, if defined, otherwise with specific bank account name (e.g. KB Sparkonto). The majority of the Service Providers comply with recommendation.

**Action Point**
@ XS2A stream lead: Check how strong recommendation shall be published.

**Comment by svenbiellmann** [comment]
### Meeting Notes 7.12.23

The proposition with the strong recommendation in the API specs (for V4) and the raising request at SIX ISO working group for documentation in SIX SPS 2025 November was agreed.
