### ISSUE TITLE
Cut-off times and/or out-of-service times of the service provider available via bLink (possibly directory)

### ISSUE THREAD

**Issue by Jammy42** [swissfintechinnovations/ca-payment#30]
There should be a time table / schedule available where a consumer of a service provider can check, when the services are available or not.

- In case of "same day" payments - so that the service user can automatically/dynamically display to the end user, when the payment will be executed and/or adjust execution date

- When the services are "open for business" - there are cases when the services of the service provider are not available (scheduled). So a schedule would be nice so that a call to a service provider can only be made, if it's according to the schedule

- When there is an unexpected outage - for example if a service user has a outage, that this information can also be obtained by bLink. Currently a service user realizes this and the issue gets spread across the bLink community by "word of mouth"

**Comment by rudiriegel** [comment]
Shouldn't the information be passed with the response to the call? With such information in the responses the consumer of the service (Service User) will always know what applies to that specific payment and can act accordingly

**Comment by ochatelain** [comment]
I would appreciate a kind of healthcheck ping by SIX, that results in some kind of alert if it fails.

**Comment by rudiriegel** [comment]
The healthcheck applies only for the outage of the service. I agree, SIX could help with this. Here we should go further than only healthcheck calls, which only provides the availability of the API Gateway. We should aim for real service calls (AIS and PSS) which are performed by SIX to all Service Providers each specific period of time (e.g. 10 minutes). SIX could then expose if the calls were successful or not.  But for this we need help from Service Providers who need to set up a test account. Definitely worth a discussion.

**Comment by svenbiellmann** [comment]
Breakout session will be organized to deep dive into the topic and better understand the needs and to define the next steps.

**Comment by svenbiellmann** [comment]
Relates to issue no. 10 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/25fc8df2-6880-47f3-8015-0550319d9589)

**Comment by svenbiellmann** [comment]
### Meeting Notes 2.11.23
This topic is not API specific and need to be discussed on a higher level.  

SIX has agreed that this will be discussed bilaterally and can be closed from this board.

**Comment by svenbiellmann** [comment]
Issue will be closed as decided in the meeting on 2.11.23.
