### ISSUE TITLE
AIS issue with respect to missing booking information for consumer bank in bLink Multibanking

### ISSUE THREAD

**Issue by RaulGuirao** [swissfintechinnovations/ca-payment#4]
Due to the fact that the element for related booking information in camt message and JSON is specified as optional and not mandatory the relevant booking information are missing.
 
In order to visualize the issue I have taken a print screen from the ZKB eBanking (Multibanking via bLink) from UBS bank accounts. There is the wide empty space where the valuable booking information of merchant and payment method should be filled with.
The information on the right prints screen (UBS eBanking) need to be exchanged for Multibanking via bLink as to provide this information as booking text.
 
We consider this issue as critical for the market acceptance of Multibanking service and are convinced that it needs to be solved in timely manner in order to provide the excellent user experience that we strive for our Multibanking service.
--> Printscreen with visualization of missing booking informaiton attached
![visualization of missing booking information](https://user-images.githubusercontent.com/117303403/199554730-83e8cce3-ee00-458d-8723-7c4670e76607.png)

The booking information is captured in the element Additional Entry Information. This element is specified as optional. Please look at the SIX specification under folder blink-api-docs-1.1.0.7\handbook\Account_Information_Service_(AIS).html:
--> Printscreen with related element attached
![Element AdditionalEntryInformation_SIX specs](https://user-images.githubusercontent.com/117303403/199554762-506be58d-3e8d-48b4-a457-974b7f7e58fd.png)

We suggest that this topic will be taken up on our next meeting as to
1.	inform about this issue and create awareness in the community
2.	clarify when the SIX specs can be adjusted in other to put this element as mandatory

**Comment by svenbiellmann** [comment]
Relates to issue no. 6 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/bcfad666-0ba4-4845-80aa-5311f83b496e)
