### ISSUE TITLE
Date parameter for /accounts/balance

### ISSUE THREAD

**Issue by simonmeyerm** [swissfintechinnovations/ca-payment#5]
Date parameter in the /balance endpoint is missing. How could the balance for a specific day be requested?
balance - blink AIS
![bLink AIS](https://user-images.githubusercontent.com/115779682/203094554-ab071553-f524-4139-a729-b9d7fa7da507.png)

balance - common-API
![Common-API](https://user-images.githubusercontent.com/115779682/203094578-1210977b-c0bb-41f0-a57f-57deba02bd0c.png)

**Comment by dkoeni** [comment]
Done.
