### ISSUE TITLE
Add - GET /iso20022/statements/{iban} similar /accounts/{iban}/transaction

### ISSUE THREAD

**Issue by chatelao** [swissfintechinnovations/ca-payment#51]
IS
- Statements cannot be requested by accountor or by date ranges.

SHOULD
- Add an endpoint similar to "/accounts/{iban}/transaction" to query statements.
- Allow dateFrom / dateTo query parameters.
- Use the same result parameters as the existing "/iso20022/statements".

**Comment by fredaspen1** [comment]
First of all orry for this message cause i don't know if it is the right place to post it.
We are looking for iso20022 dev.
We work on a payment platform for financial institutions using stablecoin. If you can impliment ISO20022 messaging standard, please send us a mail:

frederic.assom@outlook.fr

**Comment by svenbiellmann** [comment]
Item can be closed.

**Comment by svenbiellmann** [comment]
Will be implemented with #22.

**Comment by svenbiellmann** [comment]
### Meeting Notes 2.11.23
Issue will be closed.
