### ISSUE TITLE
List of transaction to an account for multibanking solution - booked / pending transactions

### ISSUE THREAD

**Issue by svenbiellmann** [swissfintechinnovations/ca-payment#54]
In order to be able to display all transactions for an account in a user-friendly manner in a multibanking solution, the question arises as to whether the existing GET /accounts/{accountId}/transactions functionality is sufficient (keyword provisional bookings). 
From my point of view, the same list of transactions to an account must be delivered via the corresponding functionality in the AIS API as when I browse the transactions in the eBanking/Mobile Banking solution of the bank to which the account belongs.

**Comment by Common-API-ch** [comment]
Feedback on behalf of UBS (due to access restrictions regarding GitHub):
For our target multibanking solution it’d be good/desired to provide “provisional bookings” through the AIS operation GET /accounts/{accountId}/transactions.
However, this is not a requirement for the MVP, and it’d rather be something to be considered for a second release.

**Comment by svenbiellmann** [comment]
Define a separate endpoint, postpone further discussions in the context of API version 5.0

**Comment by svenbiellmann** [comment]
Relates to issue no. 4 in the SIX Orchestration Project «Multibanking for Individuals»

![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/7176db75-3d59-4cc5-83dd-dfd7ed808bbf)

**Comment by svenbiellmann** [comment]
### Notes 2.11.23
This topic requires major changes for XML and JSON. The proposal is that this change will be postponed and shall be considered for implementation in V5 (autumn 2025).

**Comment by svenbiellmann** [comment]
The change request is temporarily moved to the backlog until the topic is taken up again together with the other changes proposed for version v5.

**Comment by svenbiellmann** [comment]
Topic is addressed with issue #115 and pull request #130. Therefore this issue can be closed.

**Comment by svenbiellmann** [comment]
Topic is already addressed with issue #115 and pull request #130. Therefore this issue can be closed as not planned.
