### ISSUE TITLE
Adjustment ExchangeRate Account/transactions

### ISSUE THREAD

**Issue by simonmeyerm** [swissfintechinnovations/ca-payment#63]
The exchangeRate on the /transactions endpoint in AccountAPI need to be adjusted. The pattern was initially wrongly defined and causes issues on bLink production environment.

The pattern should be changed as followed:
Old: [0-9][.][0-9]{1,10}
New: ^\\d{1,11}$|^(?=\\d+[.]\\d+$).{3,12}$

With the new pattern we would comply to the definition in the camt.053 schema:
![image](https://github.com/swissfintechinnovations/ca-payment/assets/115779682/630a432f-d08e-4404-8931-c845d5c378eb)

The definition in camt.053 does not imply how many digits before the decimal point are required, whereas the current pattern on the JSON endpoint does.

**Comment by svenbiellmann** [comment]
@dkoeni please transfer/implement with version 1.6 of SFTI API.

**Comment by dkoeni** [comment]
Hello @simonmeyerm 

My understanding from the meeting on the camt.053 related changes is that we want the adjustment from one number before the dot to multiple numbers before the dot. Your proposed regex does not implement this exclusively. Could you please clarify if and why this is the case or if the regex needs to be adapted?

**Comment by svenbiellmann** [comment]
Draft release V1.6 will be presented on next meeting 6th December 2023.
