### ISSUE TITLE
Additional Parameters for Standing Orders

### ISSUE THREAD

**Issue by CommonAPI-Admin** [swissfintechinnovations/ca-payment#69]
Besides the regular parameters (as for payments), there are some special standing order parameters needed for standing orders.

| What | Comments | Common API | NextGenPSD2 |
| -- | -- | -- | -- |
| endToEndId | Specific end to end ID | yes | yes |
| executionMode | The code of execution mode defines when or how standing order will be cancelled, processed the last time.UNTIL_DATE - standing order is valid until specific date - field lastExecutionDate.UNTIL_CANCELLATION - standing order is valid forever and must be cancelled by client. | yes | no |
| executionRule | "following" or "preceding" supported as values.This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday.The payment is then executed either the "preceding" or "following" working day.ASPSP might reject the request due to the communicated value, if rules in Online-Banking are not supportingthis execution rule. | yes | yes |
| frequencyCode | The following codes from the "EventFrequency7Code" of ISO 20022 are supported. "Daily", "Weekly", "EveryTwoWeeks",  "Monthly", "EveryTwoMonths", "Quarterly", "SemiAnnual", "Annual" | yes | yes |
| dayOfExecution | Day of execution as string. This string consists of up two characters. Leading zeroes are not allowed. 31 is ultimo of the month. | yes | yes |
| startDate | The first applicable day of execution starting from this date is the first payment. | yes | yes |
| endDate | Date when the last order will be processed. Null value responds to ending by the user. | yes | yes | 
| executionBreaksArray ofvalidFromDate*: datevalidToDate*: date | List of break periods.Start date of one break period. Standing order will not be processed from this date. Date format YYYY-MM-DD.End date of one break period. Standing order will not be processed to this date. Date format YYYY-MM-DD. | yes | no |

**Comment by svenbiellmann** [comment]
Standing order are already part of payment API. All mentioned parameters are already considered. Issue will be closed without any further actions.
