### ISSUE TITLE
intraday balance - amend/adapt description

### ISSUE THREAD

**Issue by svenbiellmann** [swissfintechinnovations/ca-payment#89]
With regard to the Kaspar& use case on bLink we got and get a lot of questions about what "kind" of balance will be returned by the GET /accounts/{accountId}/balance endpoint when called without a date. The current description seems to be not clear enough.

Proposal would be to adapt the description along the ISO20022 descriptions below.

**Comment by ochatelain** [comment]
The "BalanceType" according to ISO20022 define the following subtypes. Maybe there is a solution within the other types?


| Code | Name | Definition
-- | -- | -- | --
1 | CLAV | ClosingAvailable | Closing balance   of amount of money that is at the disposal of the account owner on the date   specified.
2 | CLBD | ClosingBooked | Balance   of the account at the end of the pre-agreed account reporting period. It is   the sum of the opening booked balance at the beginning of the period and all   entries booked to the account during the pre-agreed account reporting period.
3 | FWAV | ForwardAvailable | Forward   available balance of money that is at the disposal of the account owner on   the date specified.
4 | INFO | Information | Balance   for informational purposes.
5 | ITAV | InterimAvailable | Available   balance calculated in the course of the account servicer's business day, at   the time specified, and subject to further changes during the business day.   The interim balance is calculated on the basis of booked credit and debit   items during the calculation time/period specified.
6 | ITBD | InterimBooked | Balance   calculated in the course of the account servicer's business day, at the time   specified, and subject to further changes during the business day. The   interim balance is calculated on the basis of booked credit and debit items   during the calculation time/period specified.
7 | OPAV | OpeningAvailable | Opening   balance of amount of money that is at the disposal of the account owner on   the date specified.
8 | OPBD | OpeningBooked | Book   balance of the account at the beginning of the account reporting period. It   always equals the closing book balance from the previous report.
9 | PRCD | PreviouslyClosedBooked | Balance   of the account at the previously closed account reporting period. The opening   booked balance for the new period has to be equal to this balance.     Usage: the previously booked closing balance should equal (inclusive date)   the booked closing balance of the date it references and equal the actual   booked opening balance of the current date.
10 | XPCD | Expected | Balance,   composed of booked entries and pending items known at the time of   calculation, which projects the end of day balance if everything is booked on   the account and no other entry is posted.

**Comment by svenbiellmann** [comment]
Here is the excerpt from the [Swiss Business Rules SPS](https://www.six-group.com/dam/download/banking-services/standardization/sps/business-rules-sps-2021-de.pdf):
![image](https://github.com/swissfintechinnovations/ca-payment/assets/121558620/88deb941-6e12-43ec-aaa9-7de269e9e859)

**Comment by RaulGuirao** [comment]
ZKB delivers the ITBD (interim booked) balance for the current day when it is called without no date (in line with the API specs).

**Comment by svenbiellmann** [comment]
### Meeting Notes 4.4.24

It was agreed to align the current description to definition of ITBD according to ISO 20022. 

The pull request will be prepared and discussed on next meeting. 

It was stated that in case that a service provider is not able to provide ITBD for a specific day (e.g. weekend, holiday) the response code 204 has to be returned.
